# Generated by Django 5.0.6 on 2024-07-18 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto', '0002_coinwidget'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('price', models.CharField(max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='coinwidget',
            name='name',
        ),
        migrations.DeleteModel(
            name='Coin',
        ),
        migrations.DeleteModel(
            name='CoinWidget',
        ),
    ]
