# Generated by Django 5.0.6 on 2024-07-23 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crypto', '0003_mymodel_remove_coinwidget_name_delete_coin_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MyModel',
            new_name='favouritePages',
        ),
        migrations.RenameField(
            model_name='favouritepages',
            old_name='price',
            new_name='url',
        ),
    ]
