# Generated by Django 5.0.6 on 2024-07-24 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crypto', '0006_favouritepages_idnum'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favouritepages',
            name='idnum',
        ),
    ]
